=== Vicky18-2/IT-texn/Ticket.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://nure/it-texn/pz"
            xmlns:tns="http://nure/it-texn/pz"
            elementFormDefault="qualified">
    <xsd:element name="tickets">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="ticket" type="tns:ticket" maxOccurs="unbounded" minOccurs="1"/>
            </xsd:sequence>
        </xsd:complexType>
        <xsd:unique name="ticket_id">
            <xsd:selector xpath="tns:ticket"/>
            <xsd:field xpath="@id"/>
        </xsd:unique>
    </xsd:element>

    <xsd:complexType name="ticket">
        <xsd:all>
            <xsd:element name="ticket_price" type="xsd:decimal" minOccurs="1"/>
            <xsd:element name="session" type="tns:session" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="film" type="tns:film" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="hall" type="tns:hall" minOccurs="1" maxOccurs="1"/>
        </xsd:all>
        <xsd:attribute name="id" type="xsd:int" use="required"/>
    </xsd:complexType>

    <xsd:simpleType name="ticket_price">
        <xsd:restriction base="xsd:decimal">
            <xsd:fractionDigits value="1"/>
            <xsd:totalDigits value="3"/>
            <xsd:minInclusive value="50"/>
            <xsd:maxInclusive value="350"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="session">
        <xsd:choice>
            <xsd:sequence minOccurs="0">
                <xsd:element name="session_date" type="xsd:date"/>
                <xsd:element name="session_time" type="xsd:time"/>
            </xsd:sequence>
            <xsd:element name="session_date_and_time" type="xsd:dateTime" minOccurs="0"/>
        </xsd:choice>
    </xsd:complexType>

    <xsd:complexType name="film">
        <xsd:sequence>
            <xsd:element name="title" type="xsd:token" minOccurs="1"/>
            <xsd:element name="director" type="xsd:token" minOccurs="1" maxOccurs="2"/>
            <xsd:element name="film_duration" type="xsd:time" minOccurs="1"/>
            <xsd:element name="description" type="xsd:string" minOccurs="0"/>
            <xsd:element name="genre" type="xsd:token" minOccurs="1"/>
            <xsd:element name="language"  minOccurs="0"/>
        </xsd:sequence>
        <xsd:attribute name="lang" type="xsd:token"/>
    </xsd:complexType>

    <xsd:simpleType name="description">
        <xsd:restriction base="xsd:string">
            <xsd:minLength value="2"/>
            <xsd:maxLength value="150"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="genre">
        <xsd:restriction base="xsd:token">
            <xsd:enumeration value="Mystery"/>
            <xsd:enumeration value="Comedy"/>
            <xsd:enumeration value="Fantasy"/>
            <xsd:enumeration value="Fiction"/>
            <xsd:enumeration value="Drama"/>
            <xsd:enumeration value="Horror"/>
        </xsd:restriction>
    </xsd:simpleType>


    <xsd:simpleType name="lang">
        <xsd:restriction base="xsd:token">
            <xsd:maxLength value="3"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="hall">
        <xsd:sequence>
            <xsd:element name="hall_type" type="xsd:string" minOccurs="1"/>
            <xsd:element name="column_id" type="xsd:int"/>
            <xsd:element name="seat_id" type="xsd:token"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:simpleType name="hall_type">
        <xsd:restriction base="xsd:token">
            <xsd:length value="2"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="seat_id">
        <xsd:restriction base="tns:lang">
            <xsd:pattern value="[A-P]"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="column_id">
        <xsd:restriction base="xsd:int">
            <xsd:minExclusive value="0"/>
            <xsd:maxExclusive value="5"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="id">
        <xsd:restriction base="xsd:int">
            <xsd:minInclusive value="1"/>
        </xsd:restriction>
    </xsd:simpleType>

</xsd:schema>

=== Vicky18-2/IT-texn/IT_texn_parsers_pz2/TicketJavaDOM.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><tickets xmlns="http://nure/it-texn/pz" xmlns:tns="http://nure/it-texn/pz" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://nure/it-texn/pz Ticket.xsd"> <tns:ticket id="1">
<tns:ticket_price>2000</tns:ticket_price>
<tns:session><tns:session_date>2000-10-20</tns:session_date>
<tns:session_time>11:11:11</tns:session_time>
</tns:session>
<tns:film>
<tns:title>nam</tns:title>
<tns:director>[dir, ddd]</tns:director>
<tns:film_duration>02:02:02</tns:film_duration>
<tns:description>desc</tns:description>
<tns:genre>Comedy</tns:genre>
<tns:language>ru</tns:language>
</tns:film>
<tns:hall>
<tns:hall_type>3D</tns:hall_type>
<tns:column_id>1</tns:column_id>
<tns:seat_id>A</tns:seat_id>
</tns:hall>
</tns:ticket>
 <tns:ticket id="2">
<tns:ticket_price>2000</tns:ticket_price>
<tns:session><tns:session_date>2000-10-20</tns:session_date>
<tns:session_time>11:11:11</tns:session_time>
</tns:session>
<tns:film>
<tns:title>rip</tns:title>
<tns:director>[dir, dd]</tns:director>
<tns:film_duration>01:01:01</tns:film_duration>
<tns:description>desc</tns:description>
<tns:genre>gg</tns:genre>
<tns:language>lan</tns:language>
</tns:film>
<tns:hall>
<tns:hall_type>3D</tns:hall_type>
<tns:column_id>1</tns:column_id>
<tns:seat_id>R</tns:seat_id>
</tns:hall>
</tns:ticket>
 </tickets>

=== Vicky18-2/IT-texn/IT_texn_parsers_pz2/Ticket.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="Ticket.xsl"?>
<tickets xmlns="http://nure/it-texn/pz"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://nure/it-texn/pz Ticket.xsd"
         xmlns:tns="http://nure/it-texn/pz">

    <tns:ticket id="1">

        <tns:ticket_price>120.5</tns:ticket_price>

        <tns:session>
            <tns:session_date>2020-10-20</tns:session_date>
            <tns:session_time>12:10:00</tns:session_time>
        </tns:session>

        <tns:film lang="RU">
            <tns:title>The Emperor's</tns:title>
            <tns:director>Fernan</tns:director>
            <tns:film_duration>02:10:00</tns:film_duration>
            <tns:description>Good film</tns:description>
            <tns:genre>Mystery</tns:genre>
            <tns:language>Russian</tns:language>
        </tns:film>

        <hall>
            <tns:hall_type>3D</tns:hall_type>
            <tns:column_id>1</tns:column_id>
            <tns:seat_id>B</tns:seat_id>
        </hall>

    </tns:ticket>

    <tns:ticket id="2">

        <tns:ticket_price>150</tns:ticket_price>

        <tns:session>
            <tns:session_date>2020-11-20</tns:session_date>
            <tns:session_time>13:00:00</tns:session_time>
        </tns:session>

        <tns:film lang="RU">
            <tns:title>King</tns:title>
            <tns:director>Kerdl</tns:director>
            <tns:film_duration>02:00:00</tns:film_duration>
            <tns:description>Not good film</tns:description>
            <tns:genre>Comedy</tns:genre>
            <tns:language>English</tns:language>
        </tns:film>

        <hall>
            <tns:hall_type>2D</tns:hall_type>
            <tns:column_id>1</tns:column_id>
            <tns:seat_id>A</tns:seat_id>
        </hall>

    </tns:ticket>

</tickets>
